info:
  artifactId: "${project.name}"
  version: "${project.version}"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starwars?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

integration:
  swapi-client:
    base-url: https://swapi.co/api
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.3